version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    restart: on-failure
    ports:
      - 3306:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: drakory/georeport_golang:latest
    restart: always
    env_file:
      - /home/ubuntu/georeport/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - /home/ubuntu/georeport/.env:/app/.env

volumes:
  postgres: