version: '3.9'

services:
  database:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  golang:
    image: drakory/georeport_golang:latest
    container_name: golang_container
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - database
  react:
    image: drakory/georeport_react:latest
    container_name: react_container
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - golang
      - database

volumes:
  postgres: