version: '3.9'
services:
  database:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: on-failure
    volumes:
     - ./mariadb:/var/lib/mysql
    ports:
      - 3306:3306   
  app:
    container_name: golang_container
    build: .
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - database