version: '3.9'
services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    restart: on-failure
    volumes:
     - ${PWD}/backend/postgres:/var/lib/postgresql/data
    ports:
      - 3306:5432   
  app:
    container_name: golang_container
    build: ./backend
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ./backend:/app
    depends_on:
      - database
#  react:
#    container_name: app_frontend 
#    build: ./frontend
#    ports:
#      - 3001:3000
#    restart: on-failure
#    volumes:
#      - ./frontend:/app
#    depends_on:
#      - app